export enum ExceptionName {
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INTERNAL_EXCEPTION = 'INTERNAL_EXCEPTION',
  NOT_FOUND = 'NOT_FOUND',
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  CONFLICT = 'CONFLICT',
}
